=== og88/UWF_Undergrad/Fall 2018/Advance Computer Programing/sources/10XML/DTDExample/items.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT items (item+)>
<!ELEMENT item (product, quantity)>
<!ELEMENT product (description, price)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>

=== og88/UWF_Undergrad/Fall 2018/Advance Computer Programing/sources/10XML/DTDExample/test.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE items SYSTEM "items.dtd">
<items>
  <item>
    <product>
      <description>Toaster</description>
      <price>29.95</price></product>
    <quantity>3</quantity>
  </item>
  <item>
    <product>
      <description>Bicycle</description>
      <price>124.95</price>
    </product>
    <quantity>5</quantity>
  </item>
  <item>
    <product>
      <description>Hair dryer</description>
      <price>24.95</price>
    </product>
    <quantity>1</quantity>
  </item>
</items>
